#!/usr/bin/env python3
"""Lint docs/schema/*.md and (re)generate docs/schema/UNKNOWNS.md.

Rows live in markdown tables whose header is
`| Field | Meaning | Status | Evidence | Code |`. See docs/schema/README.md.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "docs" / "schema"
HEADER = ["Field", "Meaning", "Status", "Evidence", "Code"]
STATUSES = {"verified", "observed", "spec-only", "assumed", "unknown"}
NOT_VERIFIED = STATUSES - {"verified"}
PATH_RE = re.compile(r"`([^`]+)`")
REPO_PREFIXES = ("parser/", "docs/", "spec/", "tools/", "output/")


def cells(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def rows(path):
    """Yield (lineno, cells) for schema table rows; header errors are yielded as strings."""
    in_table = False
    for n, line in enumerate(path.read_text().splitlines(), 1):
        if not line.lstrip().startswith("|"):
            in_table = False
            continue
        c = cells(line)
        if not in_table:
            in_table = c[:1] == ["Field"] or c[:3] == HEADER[:3]
            if in_table and c != HEADER:
                yield n, f"table header must be {HEADER}, got {c}"
                in_table = False
            continue
        if set("".join(c)) <= set("-: "):
            continue
        yield n, c


def check_paths(text, where, errs):
    for m in PATH_RE.finditer(text):
        p = m.group(1).split("::")[0].split(":")[0].split("#")[0]
        if p.startswith(REPO_PREFIXES) and not any(ch in p for ch in "*<> {"):
            if not (ROOT / p).exists():
                errs.append(f"{where}: path not found: {p}")


def lint():
    errs, unknown = [], []
    files = sorted(p for p in SCHEMA.glob("*.md") if p.name not in ("README.md", "UNKNOWNS.md"))
    for f in files:
        for n, c in rows(f):
            where = f"{f.name}:{n}"
            if isinstance(c, str):
                errs.append(f"{where}: {c}")
                continue
            if len(c) != 5:
                errs.append(f"{where}: expected 5 cells, got {len(c)}")
                continue
            field, meaning, status, evidence, code = c
            status = status.strip("`")
            if status not in STATUSES:
                errs.append(f"{where}: bad status {status!r}")
                continue
            if not evidence or evidence == "-":
                errs.append(f"{where}: evidence required for {status}")
            if status == "verified" and not PATH_RE.search(evidence):
                errs.append(f"{where}: verified needs a resolving check path in backticks")
            check_paths(evidence, where, errs)
            check_paths(code, where, errs)
            if status in NOT_VERIFIED:
                unknown.append((status, f.name, n, field, meaning))
    return errs, unknown


def render(unknown):
    order = ["unknown", "assumed", "spec-only", "observed"]
    out = ["# Unknowns and unverified rows", "",
           "Generated by `parser/tools/lint_schema.py --write`. Do not edit.", ""]
    for s in order:
        items = [u for u in unknown if u[0] == s]
        out += [f"## {s} ({len(items)})", ""]
        out += [f"- `{f}:{n}` {field}: {meaning}" for _, f, n, field, meaning in items] or ["(none)"]
        out.append("")
    return "\n".join(out)


def main():
    errs, unknown = lint()
    text = render(unknown)
    target = SCHEMA / "UNKNOWNS.md"
    if "--write" in sys.argv:
        target.write_text(text)
    elif not target.exists() or target.read_text() != text:
        errs.append("UNKNOWNS.md is stale; run with --write")
    for e in errs:
        print(e)
    print(f"{len(unknown)} unverified rows, {len(errs)} errors")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
